name: Main-Application CI/CD prod

on:
    push:
        branches:
            - main
        paths:
            - 'application/main-app/**'
            - 'domain/domain-module/**'
            - 'clients/feed-client/**'
            - 'clients/open-ai-client/**'
            - 'clients/sns-client/**'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    fetch-depth: 0 # 최신 코드로 배포

            -   name: ENV 파일 생성
                run: |
                    touch .env
                    echo "$ENV" > .env
                env:
                    ENV: ${{ secrets.ENV }}
                shell: bash

            -   name: Gradle 권한 부여
                run: chmod +x gradlew

            -   name: Gradle로 빌드 실행
                run: |
                    ./gradlew clean
                    ./gradlew :application:main-app:bootJar

            # 배포에 필요한 여러 설정 파일과 프로젝트 빌드파일을 zip 파일로 모아줍니다.
            -   name: zip file 생성
                run: |
                    mkdir deploy
                    cp .env ./deploy/
                    cp ./application/main-app/docker/Dockerfile ./deploy/
                    cp ./application/main-app/docker/docker-compose.minipc.yml ./deploy/
                    cp ./application/main-app/scripts/minipc-docker-deploy.sh ./deploy/
                    cp ./application/main-app/build/libs/*.jar ./deploy/
                    chmod +x ./deploy/minipc-docker-deploy.sh
                    zip -r -qq -j ./yapp-main-app.zip ./deploy

            # ZIP 파일 전송
            -   name: Transfer ZIP file use SCP
                uses: appleboy/scp-action@master
                with:
                    username: ${{ secrets.SSH_USERNAME }}
                    host: ${{ secrets.SSH_HOST }}
                    key: ${{ secrets.SSH_KEY }}
                    port: ${{ secrets.SSH_PORT }}
                    source: "./yapp-main-app.zip"
                    target: "/home/hong/app/yapp-main-application"

            # SSH 연결 후 배포 스크립트 실행
            -   name: Execute SSH command on remote server
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    port: ${{ secrets.SSH_PORT }}
                    script: |
                        REMOTE_DIR="/home/hong/app/yapp-main-application"
                        cd $REMOTE_DIR
                        unzip -o yapp-main-app.zip
                        ./minipc-docker-deploy.sh
